goog.provide('main.core');
main.core.main_screens = (function main$core$main_screens(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [main.react_native.navigation.core.bottom_tabs,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"tabBarOptions","tabBarOptions",-837723538),new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"activeTintColor","activeTintColor",1211486730),"#5cb85c",new cljs.core.Keyword(null,"inactiveTintColor","inactiveTintColor",-583273431),new cljs.core.Keyword(null,"black","black",1294279647),new cljs.core.Keyword(null,"showLabel","showLabel",-1355105431),true], null)], null),new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"Home",new cljs.core.Keyword(null,"component","component",1555936782),main.screens.home.view.view], null),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"Portfolio",new cljs.core.Keyword(null,"component","component",1555936782),main.screens.portfolio.view.view], null),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"Prices",new cljs.core.Keyword(null,"component","component",1555936782),main.screens.prices.view.view], null),new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),"Settings",new cljs.core.Keyword(null,"component","component",1555936782),main.screens.settings.view.view], null)], null)], null);
});
main.core.app_root = (function main$core$app_root(){
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [main.react_native.navigation.core.navigation_container,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [main.react_native.navigation.core.stack,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),new cljs.core.Keyword(null,"main","main",-2117802661),new cljs.core.Keyword(null,"component","component",1555936782),main.core.main_screens], null)], null)], null)], null);
});
main.core.init = (function main$core$init(){
return main.react_native.core.register_component("crypto_rn",main.core.app_root);
});

//# sourceMappingURL=main.core.js.map
